### ISSUE TITLE
Not working with multiple kubectl configs 

### ISSUE THREAD

**Issue by martinohansen** [bonnefoa/kubectl-fzf#29]
Looks like `cache_builder` doesn't work with multiple paths in KUBECONFIG

```
$ cache_builder
I0603 13:15:47.314887   38163 main.go:190] Building role blacklist from "[]"
goroutine 1 [running]:
runtime/debug.Stack(0xc00004e05b, 0x39, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/debug/stack.go:16 +0x25
kubectlfzf/pkg/util.FatalIf(0x23c7ae0, 0xc0003da750)
        /Users/anthoninbonnefoy/git-repos/kubectl-fzf/pkg/util/util.go:197 +0x3a
main.getClientConfigAndCluster(0x8, 0x22dbc70, 0xc00035d410)
        /Users/anthoninbonnefoy/git-repos/kubectl-fzf/cmd/cache_builder/main.go:176 +0x105
main.start()
        /Users/anthoninbonnefoy/git-repos/kubectl-fzf/cmd/cache_builder/main.go:222 +0xca
main.main()
        /Users/anthoninbonnefoy/git-repos/kubectl-fzf/cmd/cache_builder/main.go:250 +0x785
Fatal error: open /Users/Martin/.kube/config-k3s:/Users/Martin/.kube/config: no such file or directory

$ echo $KUBECONFIG 
/Users/Martin/.kube/config-k3s:/Users/Martin/.kube/config
```

**Comment by bonnefoa** [comment]
kubectl-fzf now relies on the default KUBECONFIG behaviour, multiple files are now managed.
